train_stepper_args:
  kernel_regu: 1.0e-2
  kernel: 'multiscale'

dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    state_dim: 589
    latent_dim: 16
    hidden_neurons: [512, 384, 320, 256, 192, 128, 64]
  decoder:
    latent_dim: 16
    state_dim: 589
    hidden_neurons: [64, 128, 192, 256, 320, 384, 512]
    pars_dims: [317, 24]

optimizer_args:
  optimizer:
    lr: 5.0e-4
    weight_decay: 1.0e-10
  scheduler:
    warmup: 50 
    max_iters: 1000

data_args:
  num_pipes: 317
  num_nodes: 272 #268
  num_time_steps: 24
  include_leak_area: False

trainer_args:
  num_epochs: 500
  patience: 25


