
dataloader_args:
  batch_size: 64
  shuffle: True
  num_workers: 4
  
model_args:
  state_dim: 65
  hidden_neurons: [64, 64]
  pars_dim: 34

optimizer_args:
  lr: 5.0e-3
  weight_decay: 1.0e-7

data_args:
  num_pipes: 34
  num_nodes: 31
  num_time_steps: 24
  include_leak_area: False

trainer_args:
  num_epochs: 1000
  patience: 50



