train_stepper_args:
  kernel_regu: 1.0e-2
  kernel: 'multiscale'

dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    state_dim: 65
    latent_dim: 8
    hidden_neurons: [32]
    embed_dim: 4
  decoder:
    latent_dim: 8
    state_dim: 65
    hidden_neurons: [32]
    embed_dim: 4
    pars_dims: [34, 24]

optimizer_args:
  optimizer:
    lr: 5.0e-4
    weight_decay: 1.0e-10
  scheduler:
    warmup: 50 
    max_iters: 1000

data_args:
  num_pipes: 34
  num_nodes: 31
  num_time_steps: 24
  include_leak_area: False

trainer_args:
  num_epochs: 1000
  patience: 50



