train_stepper_args:
  kernel_regu: 1.0e-2
  kernel: 'multiscale'

dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    state_dim: 840
    latent_dim: 32
    hidden_neurons: [256, 128]
    embed_dim: 8
  decoder:
    latent_dim: 32
    state_dim: 840
    hidden_neurons: [128, 256]
    embed_dim: 8
    pars_dims: [444, 24]

optimizer_args:
  optimizer:
    lr: 5.0e-4
    weight_decay: 1.0e-10
  scheduler:
    warmup: 50 
    max_iters: 500

data_args:
  num_pipes: 444
  num_nodes: 396
  num_time_steps: 24
  include_leak_area: False

trainer_args:
  num_epochs: 500
  patience: 25

